# Es basicamente acciones que nosotros podemos ejecutar y/o configurar en el servidor de github
# This is a basic workflow to help you get started with Actions
# Nombre del workflow
name: CI

# Controls when the workflow will run
# en que eventos se ejecutara estas tareas
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  # Permite ejecutar este flujo de trabajo manualmente desde la pestaña Acciones
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# Pasos que ejecutara este programa
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # Ejecutara una maquina de ubunto y dentro
    runs-on: ubuntu-latest
    # estos pasos
      - name: "Mostrar un mensaje"
        run: echo "Hola mundo"
    
