# Es basicamente acciones que nosotros podemos ejecutar y/o configurar en el servidor de github
# This is a basic workflow to help you get started with Actions
# Nombre del workflow
name: CI

# Controls when the workflow will run
# en que eventos se ejecutara estas tareas
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  # Permite ejecutar este flujo de trabajo manualmente desde la pestaña Acciones
  workflow_dispatch:  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# Pasos que ejecutara este programa
jobs:
  # This workflow contains a single job called "build"
  build:
    # Aqui tambien podriamos definir algunas variables de entorno
    env:
      platform: aws
      region: us-easet-1
      acount: 123456
      # Algo importante que poedmos tener es variables tanto secretas o publicas eso en el repo -> settings -> secrests and variables -> actions -> Repository secrets | Environment secrets
      user: ${{ secrets.USER }}
      password: ${{ secrets.PASSWORD }}

    # The type of runner that the job will run on
    # Ejecutara una maquina de ubunto y dentro
    runs-on: ubuntu-latest
    # estos pasos
    steps:
      - name: "Mostrar un mensaje"
        run: echo "Hola mundo"
      
      - name: "Mostrando variables de entorno"
      # tambien se puede usar condicionales
        if: ${{ env.platform == 'aws' }}
        # los secrets lo imprimira con **** ya que github detecta que son valores secretos pero eso no quiere decir que nose puedan usar para validaciones
        run: |        
          echo "Plataforma : ${{env.platform}}"
          echo "Region : ${{env.region}}"
          echo "Cuenta : ${{env.acount}}"

          echo "User secret : ${{env.user}}"
          echo "Password secret : ${{env.password}}"

      # Tambien tenemos variables por defecto que tiene github ahi nos mostrara un objetoJSON donde se vera los commits la informacion de estos la url del repo, la url del github action etc -> https://docs.github.com/en/actions/learn-github-actions/variables
      - name: "Mostrando variables por defecto"
        run: |
          echo "Evento: ${{ toJSON(github.event) }}"
          echo "Github Actor: $GITHUB_ACTOR"
          echo "Github Actor: $GITHUB_REPOSITORY"    

      # Probando con los valores secret
      - name: "Mostrando valores si el usuario es correcto"
        if: ${{ env.user == 'user' && env.password != '321' }}
        run: |
          echo "Usuario correcto"


        
    
